// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATRrrHcoc_-aoxVQ2HVs10HjSDoIeTrYY',
    appId: '1:114324179405:web:9aa62ac8e29d77b3029c84',
    messagingSenderId: '114324179405',
    projectId: 'hemtnaa',
    authDomain: 'hemtnaa.firebaseapp.com',
    storageBucket: 'hemtnaa.firebasestorage.app',
    measurementId: 'G-98NRYVPKNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzs05c5d35qUh-bObFzBnPj1QGBygwqcE',
    appId: '1:114324179405:android:e0419dd9c0d03b4e029c84',
    messagingSenderId: '114324179405',
    projectId: 'hemtnaa',
    storageBucket: 'hemtnaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCg0V--VYDcDcMMKu8C1K5omqR9o_Eiw',
    appId: '1:114324179405:ios:d0eca944f7915258029c84',
    messagingSenderId: '114324179405',
    projectId: 'hemtnaa',
    storageBucket: 'hemtnaa.firebasestorage.app',
    iosBundleId: 'com.example.hemtnaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRCg0V--VYDcDcMMKu8C1K5omqR9o_Eiw',
    appId: '1:114324179405:ios:d0eca944f7915258029c84',
    messagingSenderId: '114324179405',
    projectId: 'hemtnaa',
    storageBucket: 'hemtnaa.firebasestorage.app',
    iosBundleId: 'com.example.hemtnaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATRrrHcoc_-aoxVQ2HVs10HjSDoIeTrYY',
    appId: '1:114324179405:web:0946f788bbdabda1029c84',
    messagingSenderId: '114324179405',
    projectId: 'hemtnaa',
    authDomain: 'hemtnaa.firebaseapp.com',
    storageBucket: 'hemtnaa.firebasestorage.app',
    measurementId: 'G-ZMZTG227X3',
  );
}
